### ISSUE TITLE
添加stegseek功能？

### ISSUE THREAD

**Issue by M3thy1** [Byxs20/JpgTools#1]
添加stegseek，就可以顺便爆破密码了

**Comment by Byxs20** [comment]
没必要 我是用来解密码的 干嘛还要再集成...



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月21日(周四) 凌晨0:51
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Byxs20/JpgTools] 添加stegseek功能？ (Issue #1)




 
添加stegseek，就可以顺便爆破密码了
